version: '3.8'
services:
  web:
    image: github-api:latest
    build: .
    command: npm run dev
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - github-api

networks:
  github-api:
    driver: bridge
